trigger:
- master

pool:
  name: 'Default'

steps:
- script: |
    echo "Checking Java and Maven versions..."
    java -version
    mvn -v
  displayName: 'Check Java and Maven versions'

- script: |
    echo "Building project with Maven..."
    mvn clean install -X
  displayName: 'Build project with Maven'